### PR TITLE
Windows port

### PR DESCRIPTION
**Pull request by janbiedermann**
specs pass, needs cleanup a bit, and faciol.io PR116 (once fixed)
```
install -c tmp/x64-mingw32/iodine/3.0.1/iodine.so lib/iodine/iodine.so
cp tmp/x64-mingw32/iodine/3.0.1/iodine.so tmp/x64-mingw32/stage/lib/iodine/iodine.so
C:/Ruby30-x64/bin/ruby.exe -I'C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rspec-support-3.10.2/lib';'C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/lib' 'C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/rspec-core-3.10.1/exe/rspec' --pattern 'spec/**{,/*/**}/*_spec.rb'

Randomized with seed 49840
..................

Top 10 slowest examples (24.09 seconds, 59.0% of total time):
  Last-Modified Header overrides the header if the value is set to nil
    2.43 seconds ./spec/integration/last_modified_header_spec.rb:19
  Transfer-Encoding: chunked when the request is not chunked returns the correct body
    2.42 seconds ./spec/integration/chunked_encoding_spec.rb:18
  Transfer-Encoding: chunked when the header is downcased returns the correct Content-Length
    2.41 seconds ./spec/integration/chunked_encoding_spec.rb:25
  Transfer-Encoding: chunked when the request is chunked returns the correct body
    2.41 seconds ./spec/integration/chunked_encoding_spec.rb:18
  Transfer-Encoding: chunked when the body size is long (includes Content-Length) returns the correct Content-Length
    2.41 seconds ./spec/integration/chunked_encoding_spec.rb:25
  Transfer-Encoding: chunked when the body size is long and evenly chunked returns the correct Content-Length
    2.41 seconds ./spec/integration/chunked_encoding_spec.rb:25
  Transfer-Encoding: chunked when the header is downcased returns the correct body
    2.4 seconds ./spec/integration/chunked_encoding_spec.rb:18
  Transfer-Encoding: chunked when the request is not chunked returns the correct Content-Length
    2.4 seconds ./spec/integration/chunked_encoding_spec.rb:25
  Last-Modified Header is parseable by Time#httpdate
    2.4 seconds ./spec/integration/last_modified_header_spec.rb:4
  Transfer-Encoding: chunked when the request is chunked returns the correct Content-Length
    2.4 seconds ./spec/integration/chunked_encoding_spec.rb:25

Top 3 slowest example groups:
  Last-Modified Header
    2.41 seconds average (7.23 seconds / 3 examples) ./spec/integration/last_modified_header_spec.rb:3
  Transfer-Encoding: chunked
    2.4 seconds average (33.6 seconds / 14 examples) ./spec/integration/chunked_encoding_spec.rb:2
  Iodine
    0.00758 seconds average (0.00758 seconds / 1 example) ./spec/unit/iodine_spec.rb:1

Finished in 40.87 seconds (files took 1.36 seconds to load)
18 examples, 0 failures

Randomized with seed 49840
```

### CODE REVIEW

**Comment by janbiedermann** [comment]
There is one issue though, that i currently dont know how to handle:
https://github.com/janbiedermann/iodine/blob/5d397286c7d2600fdcfe98e8cd25db20b91c0c1c/ext/iodine/iodine_rack_io.c#L207
That will fail.
fio_uuid2fd(uuid) -> returns the pseudo fd that is used internally by facil.io and translated to a windows handle when doing io.
TCPSocket.for_fd() -> on windows expects a  pseudo fd that can be used by ruby. But ruby doesnt know how to translate facil.io's pseudo fd.
They most probably dont match.
So there a way is needed, to get a ruby fd for a existing and used and open windows handle. Don't how to achieve that.

**Comment by janbiedermann** [comment]
Ok, i know, maybe. Ruby seems to use the fds provided by Windows. We can get a fd for a handle from `_open_osfhandle()` https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-osfhandle

**Comment by janbiedermann** [comment]
Using _open_osfhandle the real SOCKET handle cannot be closed independently, _close must be used on the obtained fd and will close the fd and SOCKET handle. Lets hope it works using _close in rio_close.

**Comment by janbiedermann** [comment]
Alright, that should work now.

**Comment by janbiedermann** [comment]
one issue: it doesnt properly stop

**Comment by boazsegev** [comment]
Hi, 

#### Quick question regarding the `_open_osfhandle`  issue:

I know that [HANDLE is a `void *` (pointer)](https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types) while SOCKET is actually just a number (`unsigned long long`) which references an index in some huge array in the kernel and isn't process specific (presumably they do check permissions somehow, but 🤷🏼‍♂️)... anyway...

... I'm not too sure it's sage to use the SOCKET type we received as a HANDLE (although I suspect, from testing windows against my own malicious code, that temporary HANDLES are exactly the same as SOCKET - they are a number dressed up as a pointer that references that array but without the reference counting capabilities...)...

So, theoretically, if we lean on unverified experimentation, it should probably work without a hitch. However, isn't there a way to do it without leaning on this internal implementation detail? Maybe a way to turn SOCKET into a HANDLE [before converting to an `fd`](https://github.com/boazsegev/iodine/pull/106/files#diff-f5c46e649e234dab8997651beb1b11b1bdc9d50c0fc2b0bdb94c46e8b5a7e5b7R2895-R2901)?

#### Stop?

What do you mean it won't properly stop? Is it not getting the shutdown signal or is it looping on the shutdown sequence (waiting for all sockets to report themselves as closed)?

#### September Deadline Disruption

I should probably note that I have a huge September deadline coming up and I won't have much time for open source work this month. I'll do what I can to push this, as I'm super happy to see iodine coming to windows, but please forgive me if I'm not as fast as I could be.

Cheers,
B.

**Comment by janbiedermann** [comment]
Hi,
quick answer regarding the _open_osfhandle issue: ruby uses SOCKET as HANDLE https://github.com/ruby/ruby/blob/7c31ecd3accd75d164b4f87b0651b47f31da286d/win32/win32.c#L3353 , see line 3360
See: https://docs.microsoft.com/en-us/windows/win32/winsock/socket-handles-2
"A socket handle from a Winsock provider can be used with other non-Winsock functions ..."

Stop: rspecs using iodine will not exit the process after running, i dont know why yet, did not yet investigate, will do the next days.

September Deadline Disruption: Don't worry, should pressure on me increase, i could temporarily publish a 'isomorfeus-iodine' or something, but so far all relaxed. Thanks for your work!

**Comment by boazsegev** [comment]
Wow, your proficiency with Windows developments is quite impressive. I have a lot to catch up with :)

**Comment by boazsegev** [comment]
See if rspec sets up a signal handler for Windows and at what point. I assume rspec handles SIGINT gracefully...

facil.io also sets up signal handlers but they work differently than the ones on Linux (for example, they are single use on Windows)... maybe somewhere along the chain the signal processing doesn't signal all the handlers (facil.io usually forwards the signal to the old handler, but I will have to look deeper to figure that out).

**Review by boazsegev — APPROVED** [review]

**Comment by boazsegev** [comment]
I am slightly swamped, but again let me say: THANKS!

**Pull request merged**
