### PR TITLE
Add spec for Transfer-Encoding: chunked

### LINKED ISSUE #87: Iodine does not read chunked bodies correctly
### System Information

 - **OS**:             Linux 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux
 - **Ruby**:         2.6.3
 - **Version**:     0.7.37
 - **OpenSSL**:  OpenSSL 1.1.1d  10 Sep 2019

### Description

When the data input has a `Transfer-Encoding: chunked`, Iodine reports the body as being empty. 

### Rack App to Reproduce

```ruby
# config.ru
run ->(env) {
  body = env['rack.input'].read
  prog = File.basename($PROGRAM_NAME)

  puts "(#{prog}) Body is: '#{body}'"
  puts "(#{prog}) Body length is: #{body.length}"

  [200, {}, []]
}
```

### Testing code

```ruby
# run.rb

require 'bundler/inline'

def run_test
  pids = []
  pids << Process.spawn("puma -p 2333 --quiet")
  pids << Process.spawn("iodine -p 2334 -w 1", err: File::NULL)

  sleep 3
  printf "\n" * 3
  puts "===================="
  system 'curl -H "Transfer-Encoding: chunked" -d "payload to send" http://localhost:2333'
  puts "===================="
  system 'curl -H "Transfer-Encoding: chunked" -d "payload to send" http://localhost:2334'
  puts "===================="
  printf "\n" * 3

  sleep 3
  pids.each { |pid| Process.kill('TERM', pid) }
end

gemfile do
  source 'https://rubygems.org'
  gem 'puma'
  gem 'iodine'

  puts Iodine::VERSION
  run_test
end
```

### Expected behavior

Other Rack servers, such as Puma, will read the body to a tempfile so they can be read normally.

### Actual behavior

The body is reported as empty.

### PR DESCRIPTION
**Pull request by ianks**
This PR adds a spec for the behavior I documented in #87, hopefully you find this helps!

---

### Update

I fixed it! Let me know what you think :)

resolves #87

### CODE REVIEW

**Comment by ianks** [comment]
Womp, womp, this doesn't fully fix the issue. It properly detects the `Transfer-Encoding: chunked`, but the body chunks are still not read properly.

**Comment by ianks** [comment]
@boazsegev I've stumbed across a new case when body is not correct are not properly read when there are multiple chunks. I've added specs for it, but can't seem to figure out the solution. Can you pull this down and give it a whirl when you get a chance?

**Comment by boazsegev** [comment]
Hi @ianks ,

Thank you for discovering this issue and opening the PR!

👏🏻👏🏻👏🏻👍🏻

I’ll have a deeper look when I’m next to my computer.

Note that the updated comparison is for the value and not the header name (values aren’t guaranteed to be lowercase, though the standard requires that **this one** is).

Thanks again!
   Bo.

**Comment by ianks** [comment]
> Note that the updated comparison is for the value and not the header name (values aren’t guaranteed to be lowercase, though the standard requires that **this one** is).

Good catch. I must have accidentally removed that check.

**Comment by boazsegev** [comment]
Hi @ianks ,

Thanks again for opening the issue, submitting the PR and keeping me updated.

A few thoughts:

1. I'll merge this for sure. I love the tests, better to have good tests and fail them than miss the tests. We can always update the code in another PR before releasing the patch.

2. I'm looking into the whole logic regarding `chucked` detection and processing. I think I wrote a "quick and dirty" solution that doesn't work on all use-cases and has some faults.

     For example, it doesn't support a header value such as `gzip, chunked` (the request will end up dropping silently as if it was malformed).

3. I should probably write more unit tests in the C code. I've improved code coverage in facil.io 0.8.0 (beta)... but parsers and network coupled logic are always more difficult to isolate for unit-tests.

4. I think case sensitivity should be dropped (my fault on that one). Yes, the standard is case sensitive for the header values, but it's better to be lenient when possible.

I'm swamped this weekend, but I'll do my best to push this forwards.

Kindly,
   Bo.

**Comment by boazsegev** [comment]
Hi @ianks ,

So far I've been writing [unit tests for the C parser](https://github.com/boazsegev/facil.io/blob/e3baf61069c0e24e300ae3d799798e6a8617863f/lib/facil/http/parsers/http1_parser.h#L756-L1475) (now, temporarily broken)...

I fixed an issue with the hex conversion, improved the `chunked` detection logic (the header is now removed if redundant and the `chunked` information is cleared away from the header value).

I finally have a test where the parser fails. This means I can finally get to work the actual issue. Shouldn't be too long :)

Kindly,
   Bo.

**Comment by ianks** [comment]
Thank you so much Bo. Feel free to use / merge as much or as little of this code that you find useful 😀

**Pull request merged**
